[package]
name = "pinject"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.25"
sysinfo = "0.31.2"

[profile.release]
opt-level = "z"
lto = true
panic = 'abort'
strip = true
codegen-units = 1
